export { default as CafeSystemImg } from "./CafeSystem.png"
export { default as GithubLogo } from "./Github-logo.png"
export { default as LinkedInLogo } from "./LinkedIn-logo.png"
export { default as BusinessWebImg } from "./Business-website.png"
export { default as PersonalWebImg } from "./Personal-website.png"
export { default as LocationImg } from "./Location-img.png"
export { default as PhoneImg } from "./Phone-img.png"
export { default as EmailImg } from "./Email-img.png"
export { default as Cub3dImg } from "./Cub3d-img.png"
export { default as GithubImg } from "./Github-img.jpeg"
export { default as EvidenceImg } from "./Evidence-img.png"
export { default as AnephityImg } from "./Anephity-img.png"
export const Cub3dURL = "https://github.com/kazemsami/cub3d";
export const MinishellURL = "https://github.com/kazemsami/minishell"
export const Ft_containersURL = "https://github.com/kazemsami/ft_containers"
export const CafeSystemURL = "https://kazemsami.netlify.app/CafeSystem.mp4"
export const PersonalWebURL = "https://kazemsami.netlify.app/"
export const BusinessWebURL = "https://jp-kalamatkat.web.app/"
export const AnephityURL = "https://anephity.web.app/"
export const CPP_MODULE_URL = "https://github.com/kazemsami/cpp-module"