export { default as CafeSystemImg } from "./CafeSystem.jpg"
export { default as GithubImg } from "./Github-logo.png"
export { default as LinkedInImg } from "./LinkedIn-logo.png"
export { default as BusinessWebImg } from "./Business-website.png"
export { default as PersonalWebImg } from "./Personal-website.png"
export { default as LocationImg } from "./Location-img.png"
export { default as PhoneImg } from "./Phone-img.png"
export { default as EmailImg } from "./Email-img.png"